[tool.poetry]
name = "spaceship-titanic-model"
version = "0.1.0"
description = ""
authors = [Dombele Joao]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
